[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["cosmos_outlet"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "cosmos_outlet"
  org = "myfirstorganization001"
  version = "3.1.1"

